### ISSUE TITLE
Проблема зі шрифтами

### ISSUE THREAD

**Issue by YellowHearth1** [ZahKri/XIII-ukr#1]
![Знімок_20240509_153639](https://github.com/ZahKri/XIII-ukr/assets/111094130/ba642090-4e3e-4094-82f4-aaaa8f91c160)
![Знімок_20240509_153707](https://github.com/ZahKri/XIII-ukr/assets/111094130/cf2c51d7-605a-4dd8-8329-60679ecdd835)
![Знімок_20240509_153751](https://github.com/ZahKri/XIII-ukr/assets/111094130/b52eabee-5380-4eea-9206-4ddc68a2f1e3)

Можете надати назву шрифтів які ви використовували під час перекладу гри?

**Comment by ZahKri** [comment]
Виправлено у версії 1.0.1
